name: Alert

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: curl https://born-to-llama.onrender.com/refresh
    - name: Deploy
      run: wget -O- https://born-to-llama.herokuapp.com/rebuild-server > /dev/null
