name: Alert

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update unlisted
      run: |
      if curl https://born-to-llama.herokuapp.com/refresh
      then exit 1
      fi
    - name: Deploy to server
      run: |
      curl https://born-to-llama.herokuapp.com/rebuild-server
      then exit 1
      fi
